### ISSUE TITLE
installation issue caudes by cmake

### ISSUE THREAD

**Issue by serena-ivaldi** [robotology-playground/kdl_format_io#3]
I just followed the instructions and installed all required dependencies. Especially orocos_kdl, which is installing the following .cmake file:

/home/icub/software/share/orocos-kdl/orocos-kdl-config.cmake

where /home/icub/software is my installation prefix.
When I try to compile kdl_format_io, two different entries appear in the cmake:

 Orocos-KDL_DIR                   /home/icub/software/share/orocos-kdl                             
 orocos_kdl_DIR                   orocos_kdl_DIR-NOTFOUND            

I think this is a glitch. Especially since the associated error is:

 CMake Error at CMakeLists.txt:40 (find_package):
   Could not find module Findorocos_kdl.cmake or a configuration file for
   package orocos_kdl.

   Adjust CMAKE_MODULE_PATH to find Findorocos_kdl.cmake or set orocos_kdl_DIR
   to the directory containing a CMake configuration file for orocos_kdl.  The
   file will have one of the following names:

     orocos_kdlConfig.cmake
     orocos_kdl-config.cmake

It looks like it's trying to look for wrong files.

**Comment by traversaro** [comment]
Should have been fixed in one of the hundreds of CMake bugfixes in [iDynTree library](https://github.com/robotology/idyntree).
